name: SPW Exercise 3 Task 3
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: mvn compile
        working-directory: ./src