name: SPW Exercise 3 Task 3

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn compile
        
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test

  package:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn package
        
  deployment:
    runs-on: self-hosted
    needs: package
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
      - uses: actions/setup-java@v2
      - with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
      - run: mvn tomcat7:redeploy-only
      - run: docker rm --force tomcat
      - run: docker image rm --force game2048
      - run: echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
      - run: docker run --rm -d --name tomcat -p 8080:8080 game2048

